// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_connectionScreen_screen_init(void)
{
    ui_connectionScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_connectionScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_connectionScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectionScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectionPanel = lv_obj_create(ui_connectionScreen);
    lv_obj_set_width(ui_connectionPanel, 35);
    lv_obj_set_height(ui_connectionPanel, 50);
    lv_obj_set_x(ui_connectionPanel, -38);
    lv_obj_set_y(ui_connectionPanel, 0);
    lv_obj_set_align(ui_connectionPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_connectionPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_connectionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connectionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_connectionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connectionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connectionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deviceImage = lv_img_create(ui_connectionPanel);
    lv_img_set_src(ui_deviceImage, &ui_img_bluetooth);
    lv_obj_set_width(ui_deviceImage, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_deviceImage, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_deviceImage, 1);
    lv_obj_set_y(ui_deviceImage, -6);
    lv_obj_set_align(ui_deviceImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deviceImage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_deviceImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_label = lv_label_create(ui_connectionPanel);
    lv_obj_set_width(ui_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_label, 0);
    lv_obj_set_y(ui_label, 17);
    lv_obj_set_align(ui_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label, "BLE");
    lv_obj_set_style_text_color(ui_label, lv_color_hex(0x2E78F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textPanel = lv_obj_create(ui_connectionScreen);
    lv_obj_set_width(ui_textPanel, 85);
    lv_obj_set_height(ui_textPanel, 67);
    lv_obj_set_x(ui_textPanel, 25);
    lv_obj_set_y(ui_textPanel, 0);
    lv_obj_set_align(ui_textPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_textPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_textPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_textPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cText = lv_label_create(ui_textPanel);
    lv_obj_set_width(ui_cText, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cText, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cText, -10);
    lv_obj_set_y(ui_cText, -23);
    lv_obj_set_align(ui_cText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_cText, "Status:");
    lv_obj_set_style_text_font(ui_cText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cText1 = lv_label_create(ui_textPanel);
    lv_obj_set_width(ui_cText1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cText1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cText1, -10);
    lv_obj_set_y(ui_cText1, -11);
    lv_obj_set_align(ui_cText1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_cText1, "Not Connected");
    lv_label_set_recolor(ui_cText1, "true");
    lv_obj_set_style_text_color(ui_cText1, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cText1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cText2 = lv_label_create(ui_textPanel);
    lv_obj_set_width(ui_cText2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_cText2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_cText2, -10);
    lv_obj_set_y(ui_cText2, 12);
    lv_obj_set_align(ui_cText2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_cText2, "Connect via \nMobile App");
    lv_label_set_recolor(ui_cText2, "false");
    lv_obj_set_style_text_color(ui_cText2, lv_color_hex(0x00F5CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cText2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
}
