// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_directionPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_directionPanel, 70);
    lv_obj_set_height(ui_directionPanel, 74);
    lv_obj_set_x(ui_directionPanel, -41);
    lv_obj_set_y(ui_directionPanel, 0);
    lv_obj_set_align(ui_directionPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_directionPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_directionPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_directionPanel, lv_color_hex(0x42FAD5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_directionPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_directionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnArrow = lv_img_create(ui_directionPanel);
    lv_img_set_src(ui_turnArrow, &ui_img_start_png);
    lv_obj_set_width(ui_turnArrow, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_turnArrow, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_turnArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_turnArrow, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_turnArrow, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_speedPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_speedPanel, 35);
    lv_obj_set_height(ui_speedPanel, 33);
    lv_obj_set_x(ui_speedPanel, 36);
    lv_obj_set_y(ui_speedPanel, 2);
    lv_obj_set_align(ui_speedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_speedPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_speedPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_speedPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed = lv_label_create(ui_speedPanel);
    lv_obj_set_width(ui_speed, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_speed, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_speed, 0);
    lv_obj_set_y(ui_speed, -6);
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed, "120");
    lv_obj_set_style_text_color(ui_speed, lv_color_hex(0xFF7A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedLabel = lv_label_create(ui_speedPanel);
    lv_obj_set_width(ui_speedLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_speedLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_speedLabel, -9);
    lv_obj_set_y(ui_speedLabel, 3);
    lv_label_set_text(ui_speedLabel, "km/h");
    lv_obj_set_style_text_color(ui_speedLabel, lv_color_hex(0x00FFDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_turnPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_turnPanel, 59);
    lv_obj_set_height(ui_turnPanel, 20);
    lv_obj_set_x(ui_turnPanel, 22);
    lv_obj_set_y(ui_turnPanel, -26);
    lv_obj_set_align(ui_turnPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_turnPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_turnPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_turnPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_turnPanel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_turnPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_direction = lv_label_create(ui_turnPanel);
    lv_obj_set_width(ui_direction, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_direction, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_direction, -7);
    lv_obj_set_y(ui_direction, -14);
    lv_label_set_text(ui_direction, "Turn Left");
    lv_obj_set_style_text_font(ui_direction, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_distance = lv_label_create(ui_turnPanel);
    lv_obj_set_width(ui_distance, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_distance, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_distance, -6);
    lv_obj_set_y(ui_distance, 15);
    lv_obj_set_align(ui_distance, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_distance, "358 m");
    lv_obj_set_style_text_font(ui_distance, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryPanel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_batteryPanel1, 21);
    lv_obj_set_height(ui_batteryPanel1, 16);
    lv_obj_set_x(ui_batteryPanel1, 68);
    lv_obj_set_y(ui_batteryPanel1, -27);
    lv_obj_set_align(ui_batteryPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_batteryPanel1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_batteryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_batteryPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_batteryPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryImage = lv_img_create(ui_batteryPanel1);
    lv_img_set_src(ui_batteryImage, &ui_img_battery_indicator_100_png);
    lv_obj_set_width(ui_batteryImage, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_batteryImage, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_batteryImage, -1);
    lv_obj_set_y(ui_batteryImage, -2);
    lv_obj_set_align(ui_batteryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryImage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_batteryImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_remainDistancePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_remainDistancePanel, 60);
    lv_obj_set_height(ui_remainDistancePanel, 19);
    lv_obj_set_x(ui_remainDistancePanel, 39);
    lv_obj_set_y(ui_remainDistancePanel, 25);
    lv_obj_set_align(ui_remainDistancePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_remainDistancePanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_remainDistancePanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_remainDistancePanel, lv_color_hex(0x42FAD5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_remainDistancePanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_remainDistancePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_destinationimage = lv_img_create(ui_remainDistancePanel);
    lv_img_set_src(ui_destinationimage, &ui_img_navitation_arrow_destination_png);
    lv_obj_set_width(ui_destinationimage, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_destinationimage, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_destinationimage, -9);
    lv_obj_set_y(ui_destinationimage, 10);
    lv_obj_set_align(ui_destinationimage, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_destinationimage, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_destinationimage, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_remainDistance = lv_label_create(ui_remainDistancePanel);
    lv_obj_set_width(ui_remainDistance, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_remainDistance, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_remainDistance, 8);
    lv_obj_set_y(ui_remainDistance, 8);
    lv_obj_set_align(ui_remainDistance, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_remainDistance, "5 km");
    lv_obj_set_style_text_font(ui_remainDistance, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
}
