// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_connectionScreen
void ui_connectionScreen_screen_init(void);
lv_obj_t *ui_connectionScreen;
lv_obj_t *ui_connectionPanel;
lv_obj_t *ui_deviceImage;
lv_obj_t *ui_label;
lv_obj_t *ui_textPanel;
lv_obj_t *ui_cText;
lv_obj_t *ui_cText1;
lv_obj_t *ui_cText2;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_directionPanel;
lv_obj_t *ui_turnArrow;
lv_obj_t *ui_speedPanel;
lv_obj_t *ui_speed;
lv_obj_t *ui_speedLabel;
lv_obj_t *ui_turnPanel;
lv_obj_t *ui_direction;
lv_obj_t *ui_distance;
lv_obj_t *ui_batteryPanel1;
lv_obj_t *ui_batteryImage;
lv_obj_t *ui_remainDistancePanel;
lv_obj_t *ui_destinationimage;
lv_obj_t *ui_remainDistance;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_mapPanel;
lv_obj_t *ui_mapImage;
lv_obj_t *ui_batteryPanel2;
lv_obj_t *ui_batteryImage2;
lv_obj_t *ui____initial_actions0;

const lv_img_dsc_t *ui_imgset_[5] = {&ui_img_battery_indicator_100_png, &ui_img_battery_indicator_80_png, &ui_img_battery_indicator_60_png, &ui_img_battery_indicator_40_png, &ui_img_battery_indicator_20_png};
const lv_img_dsc_t *ui_imgset_left_[5] = {&ui_img_slight_left_png, &ui_img_left_end_png, &ui_img_off_ramp_slight_left_png, &ui_img_continue_left_png, &ui_img_left_uturn_png};
const lv_img_dsc_t *ui_imgset_right_[5] = {&ui_img_slight_right_png, &ui_img_right_end_png, &ui_img_off_ramp_slight_right_png, &ui_img_continue_right_png, &ui_img_right_uturn_png};
const lv_img_dsc_t *ui_imgset_straight_[1] = {&ui_img_straight_png};

const lv_img_dsc_t *ui_imgset_round_left_[1] = {&ui_img_round_left_270_png};
const lv_img_dsc_t *ui_imgset_round_right_[1] = {&ui_img_round_right_90_png};
const lv_img_dsc_t *ui_imgset_round_straight_[1] = {&ui_img_round_straight_180_png};

const lv_img_dsc_t *ui_imgset_finish_[1] = {&ui_img_arrival_png};
const lv_img_dsc_t *ui_imgset_start_[1] = {&ui_img_start_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_connectionScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_connectionScreen);
}
