// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

    // SCREEN: ui_connectionScreen
    void ui_connectionScreen_screen_init(void);
    extern lv_obj_t *ui_connectionScreen;
    extern lv_obj_t *ui_connectionPanel;
    extern lv_obj_t *ui_deviceImage;
    extern lv_obj_t *ui_label;
    extern lv_obj_t *ui_textPanel;
    extern lv_obj_t *ui_cText;
    extern lv_obj_t *ui_cText1;
    extern lv_obj_t *ui_cText2;

    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t *ui_Screen1;
    extern lv_obj_t *ui_directionPanel;
    extern lv_obj_t *ui_turnArrow;
    extern lv_obj_t *ui_speedPanel;
    extern lv_obj_t *ui_speed;
    extern lv_obj_t *ui_speedLabel;
    extern lv_obj_t *ui_turnPanel;
    extern lv_obj_t *ui_direction;
    extern lv_obj_t *ui_distance;
    extern lv_obj_t *ui_batteryPanel1;
    extern lv_obj_t *ui_batteryImage;
    extern lv_obj_t *ui_remainDistancePanel;
    extern lv_obj_t *ui_destinationimage;
    extern lv_obj_t *ui_remainDistance;
    // SCREEN: ui_Screen2
    void ui_Screen2_screen_init(void);
    extern lv_obj_t *ui_Screen2;
    extern lv_obj_t *ui_mapPanel;
    extern lv_obj_t *ui_mapImage;
    extern lv_obj_t *ui_batteryPanel2;
    extern lv_obj_t *ui_batteryImage2;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_battery_indicator_20_png);
    LV_IMG_DECLARE(ui_img_battery_indicator_40_png);
    LV_IMG_DECLARE(ui_img_battery_indicator_60_png);
    LV_IMG_DECLARE(ui_img_battery_indicator_80_png);
    LV_IMG_DECLARE(ui_img_battery_indicator_100_png);
    LV_IMG_DECLARE(ui_img_navitation_arrow_destination_png);

    LV_IMG_DECLARE(ui_img_start_png);
    LV_IMG_DECLARE(ui_img_arrival_png);
    LV_IMG_DECLARE(ui_img_straight_png);
    LV_IMG_DECLARE(ui_img_continue_left_png);
    LV_IMG_DECLARE(ui_img_continue_right_png);
    LV_IMG_DECLARE(ui_img_left_end_png);
    LV_IMG_DECLARE(ui_img_left_uturn_png);
    LV_IMG_DECLARE(ui_img_right_uturn_png);
    LV_IMG_DECLARE(ui_img_off_ramp_slight_left_png);
    LV_IMG_DECLARE(ui_img_off_ramp_slight_right_png);
    LV_IMG_DECLARE(ui_img_right_end_png);
    LV_IMG_DECLARE(ui_img_round_left_270_png);
    LV_IMG_DECLARE(ui_img_round_right_90_png);
    LV_IMG_DECLARE(ui_img_round_straight_180_png);
    LV_IMG_DECLARE(ui_img_slight_left_png);
    LV_IMG_DECLARE(ui_img_slight_right_png);
    LV_IMG_DECLARE(ui_img_bluetooth);
    LV_IMG_DECLARE(ui_img_wifi_png);

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
